steps:
  # Build Backend seulement
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/applydi/applydi-backend', './backend']
    
  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/applydi/applydi-backend']
    
  # Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'applydi-backend'
      - '--image'
      - 'gcr.io/applydi/applydi-backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=applydi,ENVIRONMENT=production,DATABASE_URL=postgresql://applydiuser:applydipass@34.78.169.143/applydidb'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY
